#!/system/bin/sh

while :
do
clear
echo "                    ===>  NOTE  <==="
echo ""
echo ""
echo ""
echo "[1] Untuk Mengaktifkan/Menonaktifkan Antibanned, Mohon Untuk Cek Status Antibanned Terlebih Dahulu"
echo ""
echo ""
echo ""
echo "[2] Jika Ingin Menguninstall Antibannednya, Antibannednya Mohon Dinonaktifkan Dulu"
echo ""
echo ""
echo ""
echo "[3] Jangan Gunakan Hosts, Kecuali Hosts Original/Bawaan"
echo ""
echo ""
echo ""
echo "[4] Jika Masih Terbanned, Gunakan Virtual Root RGRNS!!"
echo ""
echo ""
echo ""
echo "[5] Pastikan Module Magisk Tidak Memblokir system/bin"
echo ""
echo ""
echo ""
read -p "ANDA SUDAH MEMBACA SEMUA NOTE? [y/n] : " jawab
if [ $jawab = y ]
then
bash tebak2an
exit 0
elif [ $jawab = n ]
then
clear
echo ""
echo "      ===>  ANTIBANNED PUBG 0.16.5 SEASON 11  <==="
echo ""
echo "========================================================"
echo ""
echo "     ######    ######   ######   ##     #   ######  "
echo "     #     #  #         #     #  # #    #  #        "
echo "     ######   #         ######   #  #   #   ######  "
echo "     #  #     #   ####  #  #     #   #  #         # "
echo "     #   #    #      #  #   #    #    # #         # "
echo "     #    #    ######   #    #   #     ##   ######  "
echo ""
echo "========================================================"
echo ""
echo "            ===>  SUBSCRIBE RGRNS YT  <==="
exit 0
else
echo ""
echo "Jawab Dengan Benar!"
echo ""
read -p "Tekan [Enter] Untuk Kembali"
fi
done