#!/system/bin/sh

hijau=`echo -e "\e[32;1m"`
biru=`echo -e "\e[36;1m"`
merah=`echo -e "\e[31;1m"`
kuning=`echo -e "\e[33;1m"`
ungu=`echo -e "\e[35;1m"`
putih=`echo -e " \e[37;1m"`
while :
do
clear
echo ""
echo $putih"      ===>$hijau  ANTIBANNED$biru PUBG$merah 0.16.5$kuning SEASON$ungu 11$putih <==="
echo ""
echo $hijau"========================================================"
echo ""
echo $merah"     ######    ######   ######   ##     #   ######  "
echo "     #     #  #         #     #  # #    #  #        "
echo "     ######   #         ######   #  #   #   ######  "
echo $putih"     #  #     #   ####  #  #     #   #  #         # "
echo "     #   #    #      #  #   #    #    # #         # "
echo "     #    #    ######   #    #   #     ##   ######  "
echo ""
echo $hijau"========================================================"
echo ""
echo $biru"ANTIBANNED V2.0"
echo $putih"FOR ROOT USER ONLY!"
echo $kuning"Made By RGRNS YT"
echo $hijau"SUBSCRIBE RGRNS YT"
echo $merah"BACA NOTE SEBELUM MENGGUNAKAN ANTIBANNED!"
echo ""
echo $hijau"========================================================"
echo ""
echo $ungu"                       MAIN MENU"
echo $putih"==> [1]$kuning INSTALL ANTIBANNED"
echo $putih"==> [2]$merah AKTIFKAN ANTIBANNED"
echo $putih"==> [3]$hijau NONAKTIFKAN ANTIBANNED"
echo $putih"==> [4]$biru UNINSTALL ANTIBANNED"
echo $putih"==> [5]$kuning CEK STATUS ANTIBANNED"
echo $putih"==> [6]$hijau INFO CREATOR"
echo $putih"==> [7] KELUAR"
echo ""
echo $hijau"========================================================"
echo ""
read -p "$ungu""Masukkan Angka :$putih" pil
if [ $pil = 1 ]
then
su -c mount -o rw,remount -t yaffs2 /system
su -c cp /data/data/com.termux/files/home/antibanned/antiban_ON /system/bin
su -c cp /data/data/com.termux/files/home/antibanned/antiban_OFF /system/bin
su -c chmod 0755 /system/bin/antiban_ON
su -c chmod 0755 /system/bin/antiban_OFF
echo ""
echo $putih"===>$hijau ANTIBANNED TELAH DI INSTALL$putih<==="
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
elif [ $pil = 2 ]
then
su -c mount -o rw,remount -t yaffs2 /system
su -c mv /data/data/com.termux/files/home/antibanned/status/ANTIBANNED-NONAKTIF /data/data/com.termux/files/home/antibanned/status/ANTIBANNED-AKTIF
su -c antiban_ON
echo ""
echo $putih"===>$hijau ANTIBAN TELAH DIAKTIFKAN$putih<==="
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
elif [ $pil = 3 ]
then
su -c mount -o rw,remount -t yaffs2 /system
su -c mv /data/data/com.termux/files/home/antibanned/status/ANTIBANNED-AKTIF /data/data/com.termux/files/home/antibanned/status/ANTIBANNED-NONAKTIF
su -c antiban_OFF
echo ""
echo $putih"===>$hijau ANTIBAN TELAH DINONAKTIFKAN$putih<==="
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
elif [ $pil = 4 ]
then
su -c mount -o rw,remount -t yaffs2 /system
su -c rm /system/bin/antiban_ON
su -c rm /system/bin/antiban_OFF
echo ""
echo $putih"===>$hijau ANTIBANNED TELAH DI UNINSTALL$putih<==="
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
elif [ $pil = 5 ]
then
cd status
echo "$hijau"
ls
cd ..
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
elif [ $pil = 6 ]
then
clear
echo ""
echo $putih"      ===>$hijau  ANTIBANNED$biru PUBG$merah 0.16.5$kuning SEASON$ungu 11$putih <==="
echo ""
echo $hijau"========================================================"
echo ""
echo $merah"     ######    ######   ######   ##     #   ######  "
echo "     #     #  #         #     #  # #    #  #        "
echo "     ######   #         ######   #  #   #   ######  "
echo $putih"     #  #     #   ####  #  #     #   #  #         # "
echo "     #   #    #      #  #   #    #    # #         # "
echo "     #    #    ######   #    #   #     ##   ######  "
echo ""
echo $hijau"========================================================"
echo ""
echo $putih" ==>$kuning Youtube : RGRNS YT"
echo $putih" ==>$merah Telegram : @selowwkayy"
echo $putih" ==>$hijau Instagram : @selowwkayy"
echo $putih" ==>$biru Grup Telegram : @RGRNSYT"
echo $putih" ==> Thanks For Support"
echo ""
echo $hijau"========================================================"
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
elif [ $pil = 7 ]
then
clear
echo ""
echo $putih"      ===>$hijau  ANTIBANNED$biru PUBG$merah 0.16.5$kuning SEASON$ungu 11$putih <==="
echo ""
echo $hijau"========================================================"
echo ""
echo $merah"     ######    ######   ######   ##     #   ######  "
echo "     #     #  #         #     #  # #    #  #        "
echo "     ######   #         ######   #  #   #   ######  "
echo $putih"     #  #     #   ####  #  #     #   #  #         # "
echo "     #   #    #      #  #   #    #    # #         # "
echo "     #    #    ######   #    #   #     ##   ######  "
echo ""
echo $hijau"========================================================"
echo ""
echo $putih"            ===>$merah  SUBSCRIBE$kuning RGRNS$biru YT$putih <==="$putih
exit 0
else
echo ""
echo $putih"===>$merah PERINTAH TIDAK DIKETAHUI$putih<==="
echo ""
read -p "$ungu""Tekan [Enter] Untuk Kembali$putih"
fi
done